### ISSUE TITLE
Plusieurs "unexpected...error"

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1476]
Arrive chez plus ou moins toutes les équipes.

en essayant de:
- passer à la phase suivant
- affectuer une analyse qualité
- en répondant aux questions

En rafraîchissant la page ou reéessayant ça fini par passer.

Partie DMP2019

**Comment by maxencelaurent** [comment]
```
production-payara-1 | java.lang.NullPointerException: null
production-payara-1 | 	at com.wegas.core.ejb.ScriptFacade$CachedScript.access$100(ScriptFacade.java:77)
production-payara-1 | 	at com.wegas.core.ejb.ScriptFacade.injectStaticScript(ScriptFacade.java:391)
production-payara-1 | 	at com.wegas.core.ejb.ScriptFacade.populate(ScriptFacade.java:261)
production-payara-1 | 	at com.wegas.core.ejb.ScriptFacade.instantiateScriptContext(ScriptFacade.java:197)

```
