### ISSUE TITLE
Impossible de redémarrer le serveur de mon côté :(

### ISSUE THREAD

**Issue by IamFonky** [Heigvd/Wegas#1544]
Juste après avoir merge master sur ma branche j'ai un souci ( #1535 , comit ff96f5052de75ab693a7f9ce6b600ae5ccf436af).
J'ai le même problème quand j'essaie de lancer master (même après un clean install :no_mouth: ).

Voici la stack trace coté serveur
```
[2020-04-09T15:36:10.062+0200] [] [SEVERE] [AS-WEB-CORE-00108] [javax.enterprise.web.core] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1586439370062] [levelValue: 1000] [[
  ContainerBase.addChild: start: 
org.apache.catalina.LifecycleException: java.lang.RuntimeException: liquibase.exception.MigrationFailedException: Migration failed for change set dbchangelogs/1574090984.xml::1574090984-10::jarle:
     Reason: liquibase.exception.DatabaseException: Error executing SQL CREATE TABLE surveydescriptor (id int8 NOT NULL, description_id int8, descriptionend_id int8, CONSTRAINT surveydescriptor_pkey PRIMARY KEY (id)): ERROR: relation "surveydescriptor" already exists:
          Caused By: Error executing SQL CREATE TABLE surveydescriptor (id int8 NOT NULL, description_id int8, descriptionend_id int8, CONSTRAINT surveydescriptor_pkey PRIMARY KEY (id)): ERROR: relation "surveydescriptor" already exists:
          Caused By: ERROR: relation "surveydescriptor" already exists
        at org.apache.catalina.core.StandardContext.start(StandardContext.java:5760)
        at com.sun.enterprise.web.WebModule.start(WebModule.java:619)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:956)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:939)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:684)
        at com.sun.enterprise.web.WebContainer.loadWebModule(WebContainer.java:1868)
        at com.sun.enterprise.web.WebContainer.loadWebModule(WebContainer.java:1604)
        at com.sun.enterprise.web.WebApplication.start(WebApplication.java:107)
        at org.glassfish.internal.data.EngineRef.start(EngineRef.java:123)
        at org.glassfish.internal.data.ModuleInfo.start(ModuleInfo.java:280)
        at org.glassfish.internal.data.ApplicationInfo.start(ApplicationInfo.java:344)
        at com.sun.enterprise.v3.server.ApplicationLifecycle.initialize(ApplicationLifecycle.java:584)
        at fish.payara.deployment.admin.InitializeAllApplicationsCommand.execute(InitializeAllApplicationsCommand.java:75)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:558)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:554)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:360)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:553)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:584)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:576)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:360)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:575)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1496)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:120)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1878)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1754)
        at com.sun.enterprise.admin.cli.embeddable.CommandExecutorImpl.executeCommand(CommandExecutorImpl.java:183)
        at com.sun.enterprise.admin.cli.embeddable.CommandExecutorImpl.run(CommandExecutorImpl.java:96)
        at fish.payara.micro.impl.PayaraMicroImpl.bootStrap(PayaraMicroImpl.java:1063)
        at fish.payara.micro.impl.PayaraMicroImpl.create(PayaraMicroImpl.java:211)
        at fish.payara.micro.impl.PayaraMicroImpl.main(PayaraMicroImpl.java:200)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at fish.payara.micro.boot.loader.MainMethodRunner.run(MainMethodRunner.java:50)
        at fish.payara.micro.boot.loader.Launcher.launch(Launcher.java:114)
        at fish.payara.micro.boot.loader.Launcher.launch(Launcher.java:73)
        at fish.payara.micro.boot.PayaraMicroLauncher.create(PayaraMicroLauncher.java:87)
        at fish.payara.micro.boot.PayaraMicroLauncher.main(PayaraMicroLauncher.java:71)
        at fish.payara.micro.PayaraMicro.main(PayaraMicro.java:397)
Caused by: java.lang.RuntimeException: liquibase.exception.MigrationFailedException: Migration failed for change set dbchangelogs/1574090984.xml::1574090984-10::jarle:
     Reason: liquibase.exception.DatabaseException: Error executing SQL CREATE TABLE surveydescriptor (id int8 NOT NULL, description_id int8, descriptionend_id int8, CONSTRAINT surveydescriptor_pkey PRIMARY KEY (id)): ERROR: relation "surveydescriptor" already exists:
          Caused By: Error executing SQL CREATE TABLE surveydescriptor (id int8 NOT NULL, description_id int8, descriptionend_id int8, CONSTRAINT surveydescriptor_pkey PRIMARY KEY (id)): ERROR: relation "surveydescriptor" already exists:
          Caused By: ERROR: relation "surveydescriptor" already exists
        at liquibase.integration.servlet.LiquibaseServletListener.contextInitialized(LiquibaseServletListener.java:159)
        at org.apache.catalina.core.StandardContext.contextListenerStart(StandardContext.java:5165)
        at com.sun.enterprise.web.WebModule.contextListenerStart(WebModule.java:683)
        at org.apache.catalina.core.StandardContext.start(StandardContext.java:5738)
        ... 41 more
Caused by: liquibase.exception.MigrationFailedException: Migration failed for change set dbchangelogs/1574090984.xml::1574090984-10::jarle:
     Reason: liquibase.exception.DatabaseException: Error executing SQL CREATE TABLE surveydescriptor (id int8 NOT NULL, description_id int8, descriptionend_id int8, CONSTRAINT surveydescriptor_pkey PRIMARY KEY (id)): ERROR: relation "surveydescriptor" already exists:
          Caused By: Error executing SQL CREATE TABLE surveydescriptor (id int8 NOT NULL, description_id int8, descriptionend_id int8, CONSTRAINT surveydescriptor_pkey PRIMARY KEY (id)): ERROR: relation "surveydescriptor" already exists:
          Caused By: ERROR: relation "surveydescriptor" already exists
        at liquibase.changelog.ChangeSet.execute(ChangeSet.java:347)
        at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:27)
        at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:58)
        at liquibase.Liquibase.update(Liquibase.java:114)
        at liquibase.integration.servlet.LiquibaseServletListener.contextInitialized(LiquibaseServletListener.java:147)
        ... 44 more
Caused by: liquibase.exception.DatabaseException: Error executing SQL CREATE TABLE surveydescriptor (id int8 NOT NULL, description_id int8, descriptionend_id int8, CONSTRAINT surveydescriptor_pkey PRIMARY KEY (id)): ERROR: relation "surveydescriptor" already exists
        at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:62)
        at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:104)
        at liquibase.database.AbstractDatabase.execute(AbstractDatabase.java:1091)
        at liquibase.database.AbstractDatabase.executeStatements(AbstractDatabase.java:1075)
        at liquibase.changelog.ChangeSet.execute(ChangeSet.java:317)
        ... 48 more
Caused by: org.postgresql.util.PSQLException: ERROR: relation "surveydescriptor" already exists
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2477)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2190)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:300)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:428)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:354)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:301)
        at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:287)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:264)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:260)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.postgresql.ds.PGPooledConnection$StatementHandler.invoke(PGPooledConnection.java:424)
        at com.sun.proxy.$Proxy471.execute(Unknown Source)
        at com.sun.gjc.spi.base.StatementWrapper.execute(StatementWrapper.java:375)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.sun.gjc.spi.jdbc40.ProfiledConnectionWrapper40$1.invoke(ProfiledConnectionWrapper40.java:437)
        at com.sun.proxy.$Proxy472.execute(Unknown Source)
        at liquibase.executor.jvm.JdbcExecutor$1ExecuteStatementCallback.doInStatement(JdbcExecutor.java:92)
        at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:55)
        ... 52 more
]]

[2020-04-09T15:36:10.065+0200] [] [WARNING] [] [javax.enterprise.web] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1586439370065] [levelValue: 900] [[
  java.lang.IllegalStateException: ContainerBase.addChild: start: org.apache.catalina.LifecycleException: java.lang.RuntimeException: liquibase.exception.MigrationFailedException: Migration failed for change set dbchangelogs/1574090984.xml::1574090984-10::jarle:
     Reason: liquibase.exception.DatabaseException: Error executing SQL CREATE TABLE surveydescriptor (id int8 NOT NULL, description_id int8, descriptionend_id int8, CONSTRAINT surveydescriptor_pkey PRIMARY KEY (id)): ERROR: relation "surveydescriptor" already exists:
          Caused By: Error executing SQL CREATE TABLE surveydescriptor (id int8 NOT NULL, description_id int8, descriptionend_id int8, CONSTRAINT surveydescriptor_pkey PRIMARY KEY (id)): ERROR: relation "surveydescriptor" already exists:
          Caused By: ERROR: relation "surveydescriptor" already exists
java.lang.IllegalStateException: ContainerBase.addChild: start: org.apache.catalina.LifecycleException: java.lang.RuntimeException: liquibase.exception.MigrationFailedException: Migration failed for change set dbchangelogs/1574090984.xml::1574090984-10::jarle:
     Reason: liquibase.exception.DatabaseException: Error executing SQL CREATE TABLE surveydescriptor (id int8 NOT NULL, description_id int8, descriptionend_id int8, CONSTRAINT surveydescriptor_pkey PRIMARY KEY (id)): ERROR: relation "surveydescriptor" already exists:
          Caused By: Error executing SQL CREATE TABLE surveydescriptor (id int8 NOT NULL, description_id int8, descriptionend_id int8, CONSTRAINT surveydescriptor_pkey PRIMARY KEY (id)): ERROR: relation "surveydescriptor" already exists:
          Caused By: ERROR: relation "surveydescriptor" already exists
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:960)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:939)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:684)
        at com.sun.enterprise.web.WebContainer.loadWebModule(WebContainer.java:1868)
        at com.sun.enterprise.web.WebContainer.loadWebModule(WebContainer.java:1604)
        at com.sun.enterprise.web.WebApplication.start(WebApplication.java:107)
        at org.glassfish.internal.data.EngineRef.start(EngineRef.java:123)
        at org.glassfish.internal.data.ModuleInfo.start(ModuleInfo.java:280)
        at org.glassfish.internal.data.ApplicationInfo.start(ApplicationInfo.java:344)
        at com.sun.enterprise.v3.server.ApplicationLifecycle.initialize(ApplicationLifecycle.java:584)
        at fish.payara.deployment.admin.InitializeAllApplicationsCommand.execute(InitializeAllApplicationsCommand.java:75)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:558)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:554)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:360)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:553)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:584)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:576)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:360)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:575)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1496)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:120)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1878)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1754)
        at com.sun.enterprise.admin.cli.embeddable.CommandExecutorImpl.executeCommand(CommandExecutorImpl.java:183)
        at com.sun.enterprise.admin.cli.embeddable.CommandExecutorImpl.run(CommandExecutorImpl.java:96)
        at fish.payara.micro.impl.PayaraMicroImpl.bootStrap(PayaraMicroImpl.java:1063)
        at fish.payara.micro.impl.PayaraMicroImpl.create(PayaraMicroImpl.java:211)
        at fish.payara.micro.impl.PayaraMicroImpl.main(PayaraMicroImpl.java:200)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at fish.payara.micro.boot.loader.MainMethodRunner.run(MainMethodRunner.java:50)
        at fish.payara.micro.boot.loader.Launcher.launch(Launcher.java:114)
        at fish.payara.micro.boot.loader.Launcher.launch(Launcher.java:73)
        at fish.payara.micro.boot.PayaraMicroLauncher.create(PayaraMicroLauncher.java:87)
        at fish.payara.micro.boot.PayaraMicroLauncher.main(PayaraMicroLauncher.java:71)
        at fish.payara.micro.PayaraMicro.main(PayaraMicro.java:397)
]]

[2020-04-09T15:36:10.066+0200] [] [SEVERE] [] [javax.enterprise.system.tools.deployment.common] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1586439370066] [levelValue: 1000] [[
  Exception while invoking class com.sun.enterprise.web.WebApplication start method
java.lang.Exception: java.lang.IllegalStateException: ContainerBase.addChild: start: org.apache.catalina.LifecycleException: java.lang.RuntimeException: liquibase.exception.MigrationFailedException: Migration failed for change set dbchangelogs/1574090984.xml::1574090984-10::jarle:
     Reason: liquibase.exception.DatabaseException: Error executing SQL CREATE TABLE surveydescriptor (id int8 NOT NULL, description_id int8, descriptionend_id int8, CONSTRAINT surveydescriptor_pkey PRIMARY KEY (id)): ERROR: relation "surveydescriptor" already exists:
          Caused By: Error executing SQL CREATE TABLE surveydescriptor (id int8 NOT NULL, description_id int8, descriptionend_id int8, CONSTRAINT surveydescriptor_pkey PRIMARY KEY (id)): ERROR: relation "surveydescriptor" already exists:
          Caused By: ERROR: relation "surveydescriptor" already exists
        at com.sun.enterprise.web.WebApplication.start(WebApplication.java:136)
        at org.glassfish.internal.data.EngineRef.start(EngineRef.java:123)
        at org.glassfish.internal.data.ModuleInfo.start(ModuleInfo.java:280)
        at org.glassfish.internal.data.ApplicationInfo.start(ApplicationInfo.java:344)
        at com.sun.enterprise.v3.server.ApplicationLifecycle.initialize(ApplicationLifecycle.java:584)
        at fish.payara.deployment.admin.InitializeAllApplicationsCommand.execute(InitializeAllApplicationsCommand.java:75)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:558)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:554)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:360)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:553)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:584)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:576)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:360)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:575)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1496)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:120)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1878)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1754)
        at com.sun.enterprise.admin.cli.embeddable.CommandExecutorImpl.executeCommand(CommandExecutorImpl.java:183)
        at com.sun.enterprise.admin.cli.embeddable.CommandExecutorImpl.run(CommandExecutorImpl.java:96)
        at fish.payara.micro.impl.PayaraMicroImpl.bootStrap(PayaraMicroImpl.java:1063)
        at fish.payara.micro.impl.PayaraMicroImpl.create(PayaraMicroImpl.java:211)
        at fish.payara.micro.impl.PayaraMicroImpl.main(PayaraMicroImpl.java:200)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at fish.payara.micro.boot.loader.MainMethodRunner.run(MainMethodRunner.java:50)
        at fish.payara.micro.boot.loader.Launcher.launch(Launcher.java:114)
        at fish.payara.micro.boot.loader.Launcher.launch(Launcher.java:73)
        at fish.payara.micro.boot.PayaraMicroLauncher.create(PayaraMicroLauncher.java:87)
        at fish.payara.micro.boot.PayaraMicroLauncher.main(PayaraMicroLauncher.java:71)
        at fish.payara.micro.PayaraMicro.main(PayaraMicro.java:397)
]]

[2020-04-09T15:36:10.094+0200] [] [SEVERE] [NCLS-CORE-00026] [javax.enterprise.system.core] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1586439370094] [levelValue: 1000] [[
  Exception during lifecycle processing
java.lang.Exception: java.lang.IllegalStateException: ContainerBase.addChild: start: org.apache.catalina.LifecycleException: java.lang.RuntimeException: liquibase.exception.MigrationFailedException: Migration failed for change set dbchangelogs/1574090984.xml::1574090984-10::jarle:
     Reason: liquibase.exception.DatabaseException: Error executing SQL CREATE TABLE surveydescriptor (id int8 NOT NULL, description_id int8, descriptionend_id int8, CONSTRAINT surveydescriptor_pkey PRIMARY KEY (id)): ERROR: relation "surveydescriptor" already exists:
          Caused By: Error executing SQL CREATE TABLE surveydescriptor (id int8 NOT NULL, description_id int8, descriptionend_id int8, CONSTRAINT surveydescriptor_pkey PRIMARY KEY (id)): ERROR: relation "surveydescriptor" already exists:
          Caused By: ERROR: relation "surveydescriptor" already exists
        at com.sun.enterprise.web.WebApplication.start(WebApplication.java:136)
        at org.glassfish.internal.data.EngineRef.start(EngineRef.java:123)
        at org.glassfish.internal.data.ModuleInfo.start(ModuleInfo.java:280)
        at org.glassfish.internal.data.ApplicationInfo.start(ApplicationInfo.java:344)
        at com.sun.enterprise.v3.server.ApplicationLifecycle.initialize(ApplicationLifecycle.java:584)
        at fish.payara.deployment.admin.InitializeAllApplicationsCommand.execute(InitializeAllApplicationsCommand.java:75)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:558)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:554)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:360)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:553)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:584)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:576)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:360)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:575)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1496)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:120)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1878)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1754)
        at com.sun.enterprise.admin.cli.embeddable.CommandExecutorImpl.executeCommand(CommandExecutorImpl.java:183)
        at com.sun.enterprise.admin.cli.embeddable.CommandExecutorImpl.run(CommandExecutorImpl.java:96)
        at fish.payara.micro.impl.PayaraMicroImpl.bootStrap(PayaraMicroImpl.java:1063)
        at fish.payara.micro.impl.PayaraMicroImpl.create(PayaraMicroImpl.java:211)
        at fish.payara.micro.impl.PayaraMicroImpl.main(PayaraMicroImpl.java:200)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at fish.payara.micro.boot.loader.MainMethodRunner.run(MainMethodRunner.java:50)
        at fish.payara.micro.boot.loader.Launcher.launch(Launcher.java:114)
        at fish.payara.micro.boot.loader.Launcher.launch(Launcher.java:73)
        at fish.payara.micro.boot.PayaraMicroLauncher.create(PayaraMicroLauncher.java:87)
        at fish.payara.micro.boot.PayaraMicroLauncher.main(PayaraMicroLauncher.java:71)
        at fish.payara.micro.PayaraMicro.main(PayaraMicro.java:397)
]]

[2020-04-09T15:36:10.095+0200] [] [SEVERE] [] [javax.enterprise.system.core] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1586439370095] [levelValue: 1000] Exception while loading the app

[2020-04-09T15:36:10.249+0200] [] [SEVERE] [AS-WEB-GLUE-00192] [javax.enterprise.web] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1586439370249] [levelValue: 1000] Undeployment failed for context /Wegas

[2020-04-09T15:36:10.276+0200] [] [INFO] [] [javax.enterprise.system.container.ejb.fish.payara.ejb.timer.hazelcast] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1586439370276] [levelValue: 800] No timers to be deleted for id: 103968888723931136

[2020-04-09T15:36:10.290+0200] [] [WARNING] [NCLS-CORE-00069] [javax.enterprise.system.core] [tid: _ThreadID=108 _ThreadName=Executor-Service-8] [timeMillis: 1586439370290] [levelValue: 900] [[
  Exception while dispatching an event
java.lang.IllegalStateException: This web container has not yet been started
        at org.glassfish.web.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1571)
        at org.glassfish.web.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1528)
        at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:419)
        at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:383)
        at ch.qos.logback.classic.Logger.info(Logger.java:579)
        at com.wegas.core.Slf4jSessionLogger.log(Slf4jSessionLogger.java:111)
        at org.eclipse.persistence.internal.sessions.AbstractSession.log(AbstractSession.java:3641)
        at org.eclipse.persistence.internal.sessions.AbstractSession.log(AbstractSession.java:4880)
        at org.eclipse.persistence.internal.sessions.AbstractSession.log(AbstractSession.java:4852)
        at org.eclipse.persistence.internal.databaseaccess.DatasourceAccessor.disconnect(DatasourceAccessor.java:490)
        at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.disconnect(DatabaseAccessor.java:515)
        at org.eclipse.persistence.internal.sessions.DatabaseSessionImpl.disconnect(DatabaseSessionImpl.java:476)
        at org.eclipse.persistence.sessions.server.ServerSession.disconnect(ServerSession.java:538)
        at org.eclipse.persistence.internal.sessions.DatabaseSessionImpl.logout(DatabaseSessionImpl.java:1009)
        at org.eclipse.persistence.sessions.server.ServerSession.logout(ServerSession.java:808)
        at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.removeSessionFromGlobalSessionManager(EntityManagerSetupImpl.java:593)
        at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.undeploy(EntityManagerSetupImpl.java:3082)
        at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.close(EntityManagerFactoryDelegate.java:285)
        at org.eclipse.persistence.internal.jpa.EntityManagerFactoryImpl.close(EntityManagerFactoryImpl.java:296)
        at org.glassfish.persistence.jpa.JPADeployer.closeEMFs(JPADeployer.java:424)
        at org.glassfish.persistence.jpa.JPADeployer.event(JPADeployer.java:415)
        at org.glassfish.kernel.event.EventsImpl$1.run(EventsImpl.java:123)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
]]

[2020-04-09T15:36:10.311+0200] [] [INFO] [] [PayaraMicro] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1586439370311] [levelValue: 800] [[
  
{
    "Instance Configuration": {
        "Host": "localhost",
        "Http Port(s)": "8080",
        "Https Port(s)": "8181",
        "Instance Name": "Helpful-Whitebait",
        "Instance Group": "MicroShoal",
        "Hazelcast Member UUID": "ed1c2f1b-aa61-4dbc-866e-1371a3d7a01f",
        "Deployed": [
        ]
    }
}]]

[2020-04-09T15:36:10.325+0200] [] [INFO] [] [PayaraMicro] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1586439370325] [levelValue: 800] [[
  
Payara Micro URLs:

]]

[2020-04-09T15:36:10.325+0200] [] [INFO] [] [PayaraMicro] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1586439370325] [levelValue: 800] Payara Micro  5.194 #badassmicrofish (build 327) ready in 40,963 (ms)
```

**Comment by IamFonky** [comment]
Il semblerait que j'aie mal nettoyé la base de données la dernière fois que j'ai testé la branche survey ^^

**Comment by git-jarle** [comment]
C'est ça. Il faut supprimer manuellement les tables survey* qui ont déjà été créées lors de ta première importation de la branche "suveys".  Commande SQL:

drop table surveychoicesdescriptor, surveyinputdescriptor, surveyinputinstance, surveysectiondescriptor, surveysectioninstance, surveydescriptor, surveyinstance, surveytextdescriptor, surveynumberdescriptor cascade

**Comment by IamFonky** [comment]
Okay, merci :+1:
