### ISSUE TITLE
Player page loading errors

### ISSUE THREAD

**Issue by xgo-work** [Heigvd/Wegas#1915]
Witnessed on numerous machines of the HUG.

When starting a game as a player, the interface hangs with the following error. The game obviously doesn't load at all.

```
Un iframe possédant à la fois allow-scripts et allow-same-origin pour son attribut sandbox peut se retirer du mode bac à sable (sandboxing). [player.html](https://wegas.albasim.ch/2/player.html?id=28947487)
unreachable code after return statement
[player.js:318:12](https://wegas.albasim.ch/wegas-react/dist/player.js)
Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    React 11
    unstable_runWithPriority scheduler.production.min.js:18
    React 5
    be storeHookFactory.ts:56
    Redux 2
    
    dispatch
    
    createThunkMiddleware
    PlayerLibrariesLoader PlayerLibrariesLoader.tsx:90
[react-dom.production.min.js:216:199](webpack://wegas_react/node_modules/react-dom/cjs/react-dom.production.min.js)
    React 5
    unstable_runWithPriority scheduler.production.min.js:18
    React 4
    unstable_runWithPriority scheduler.production.min.js:18
    React 5
    be storeHookFactory.ts:56
    Redux 2
    
    dispatch
    
    createThunkMiddleware
    PlayerLibrariesLoader PlayerLibrariesLoader.tsx:90
[ClientLibrariesLoader] Cannot get client scripts
```

- This bug is non reproducible on other machines. Thus it could be some network constraints that trigger the issue.
- It is not systematic, thus it might be some loading sync issue.

Laurent Suppan asked for the possibility of getting an HUG configured machine.

**Comment by xgo-work** [comment]
Reproduced on a machine lent by the HUG.
- On Chrome, set the Network settings to "disable cache" and "Fast 3G"
- Launch a Debug HUG player game with MIMMS v2.1 beta

The following stack trace is obtained

```
react-dom.development.js:29840 Download the React DevTools for a better development experience: https://reactjs.org/link/react-devtools
sandbox.ts:121 An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can escape its sandboxing.
createSandbox @ sandbox.ts:121
./src/Components/Hooks/sandbox.ts @ sandbox.ts:159
__webpack_require__ @ bootstrap:19
./src/Helper/wegaslog.tsx @ wegasEntites.ts:43
__webpack_require__ @ bootstrap:19
./src/data/normalize/index.ts @ VariableDescriptorMethods.ts:135
__webpack_require__ @ bootstrap:19
./src/data/selectors/Helper.ts @ Global.ts:12
__webpack_require__ @ bootstrap:19
./src/data/selectors/index.ts @ VariableInstanceSelector.ts:86
__webpack_require__ @ bootstrap:19
./src/API/files.api.ts @ clientScriptHelper.ts:92
__webpack_require__ @ bootstrap:19
./src/data/Reducer/editingState.ts @ VariableInstanceReducer.ts:336
__webpack_require__ @ bootstrap:19
./src/Editor/editionConfig.ts @ FontAwesome.tsx:170
__webpack_require__ @ bootstrap:19
./src/data/actions.ts @ actionTypes.ts:72
__webpack_require__ @ bootstrap:19
./src/data/Reducer/gameModel.ts @ game.ts:50
__webpack_require__ @ bootstrap:19
./src/data/index.ts @ index.ts:159
__webpack_require__ @ bootstrap:19
./src/data/Stores/store.ts @ pageStore.ts:64
__webpack_require__ @ bootstrap:19
./src/i18n/internalTranslator.ts @ editorTabs.ts:14
__webpack_require__ @ bootstrap:19
./src/Components/Contexts/AuthorizationsProvider.tsx @ websocket.ts:418
__webpack_require__ @ bootstrap:19
(anonymous) @ nonce:1
(anonymous) @ player.js:360902
(anonymous) @ player.js:360903
react.development.js:209 Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `PageDeserializer`.
    at PageDeserializer (https://dev.albasim.ch/wegas-react/dist/player.js:26718:22)
    at div
    at Suspense
    at div
    at ThemeProvider (https://dev.albasim.ch/wegas-react/dist/player.js:29273:23)
    at DndProvider (https://dev.albasim.ch/wegas-react/dist/player.js:356903:11)
    at DefaultDndProvider (https://dev.albasim.ch/wegas-react/dist/player.js:19321:23)
    at PageLoader (https://dev.albasim.ch/wegas-react/dist/player.js:38188:29)
    at Player (https://dev.albasim.ch/wegas-react/dist/player.js:39112:60)
    at div
    at ThemeProvider (https://dev.albasim.ch/wegas-react/dist/player.js:29273:23)
    at PlayerLibrariesLoader (https://dev.albasim.ch/wegas-react/dist/player.js:20661:92)
    at ClassesHandler (https://dev.albasim.ch/wegas-react/dist/player.js:19261:23)
    at LanguagesContext (https://dev.albasim.ch/wegas-react/dist/player.js:19538:23)
    at ServerStatusManager (https://dev.albasim.ch/wegas-react/dist/player.js:28750:24)
    at FullscreenProvider (https://dev.albasim.ch/wegas-react/dist/player.js:19484:23)
    at FeaturesContext (https://dev.albasim.ch/wegas-react/dist/player.js:19373:23)
    at AuthorizationContext (https://dev.albasim.ch/wegas-react/dist/player.js:19115:23)
printWarning @ react.development.js:209
error @ react.development.js:183
createElementWithValidation @ react.development.js:2354
PageDeserializer @ PageDeserializer.tsx:265
renderWithHooks @ react-dom.development.js:16305
mountIndeterminateComponent @ react-dom.development.js:20074
beginWork @ react-dom.development.js:21587
beginWork$1 @ react-dom.development.js:27426
performUnitOfWork @ react-dom.development.js:26560
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
performConcurrentWorkOnRoot @ react-dom.development.js:25738
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
react-dom.development.js:28439 Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `PageDeserializer`.
    at createFiberFromTypeAndProps (react-dom.development.js:28439:1)
    at createFiberFromElement (react-dom.development.js:28465:1)
    at reconcileSingleElement (react-dom.development.js:15750:1)
    at reconcileChildFibers (react-dom.development.js:15808:1)
    at reconcileChildren (react-dom.development.js:19167:1)
    at finishClassComponent (react-dom.development.js:19782:1)
    at updateClassComponent (react-dom.development.js:19698:1)
    at beginWork (react-dom.development.js:21611:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
createFiberFromTypeAndProps @ react-dom.development.js:28439
createFiberFromElement @ react-dom.development.js:28465
reconcileSingleElement @ react-dom.development.js:15750
reconcileChildFibers @ react-dom.development.js:15808
reconcileChildren @ react-dom.development.js:19167
finishClassComponent @ react-dom.development.js:19782
updateClassComponent @ react-dom.development.js:19698
beginWork @ react-dom.development.js:21611
callCallback @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27451
performUnitOfWork @ react-dom.development.js:26560
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
performConcurrentWorkOnRoot @ react-dom.development.js:25738
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
react.development.js:209 Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `PageDeserializer`.
    at PageDeserializer (https://dev.albasim.ch/wegas-react/dist/player.js:26718:22)
    at div
    at Suspense
    at div
    at ThemeProvider (https://dev.albasim.ch/wegas-react/dist/player.js:29273:23)
    at DndProvider (https://dev.albasim.ch/wegas-react/dist/player.js:356903:11)
    at DefaultDndProvider (https://dev.albasim.ch/wegas-react/dist/player.js:19321:23)
    at PageLoader (https://dev.albasim.ch/wegas-react/dist/player.js:38188:29)
    at Player (https://dev.albasim.ch/wegas-react/dist/player.js:39112:60)
    at div
    at ThemeProvider (https://dev.albasim.ch/wegas-react/dist/player.js:29273:23)
    at PlayerLibrariesLoader (https://dev.albasim.ch/wegas-react/dist/player.js:20661:92)
    at ClassesHandler (https://dev.albasim.ch/wegas-react/dist/player.js:19261:23)
    at LanguagesContext (https://dev.albasim.ch/wegas-react/dist/player.js:19538:23)
    at ServerStatusManager (https://dev.albasim.ch/wegas-react/dist/player.js:28750:24)
    at FullscreenProvider (https://dev.albasim.ch/wegas-react/dist/player.js:19484:23)
    at FeaturesContext (https://dev.albasim.ch/wegas-react/dist/player.js:19373:23)
    at AuthorizationContext (https://dev.albasim.ch/wegas-react/dist/player.js:19115:23)
printWarning @ react.development.js:209
error @ react.development.js:183
createElementWithValidation @ react.development.js:2354
PageDeserializer @ PageDeserializer.tsx:265
renderWithHooks @ react-dom.development.js:16305
mountIndeterminateComponent @ react-dom.development.js:20074
beginWork @ react-dom.development.js:21587
beginWork$1 @ react-dom.development.js:27426
performUnitOfWork @ react-dom.development.js:26560
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
recoverFromConcurrentError @ react-dom.development.js:25850
performConcurrentWorkOnRoot @ react-dom.development.js:25750
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
react-dom.development.js:28439 Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `PageDeserializer`.
    at createFiberFromTypeAndProps (react-dom.development.js:28439:1)
    at createFiberFromElement (react-dom.development.js:28465:1)
    at reconcileSingleElement (react-dom.development.js:15750:1)
    at reconcileChildFibers (react-dom.development.js:15808:1)
    at reconcileChildren (react-dom.development.js:19167:1)
    at finishClassComponent (react-dom.development.js:19782:1)
    at updateClassComponent (react-dom.development.js:19698:1)
    at beginWork (react-dom.development.js:21611:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
createFiberFromTypeAndProps @ react-dom.development.js:28439
createFiberFromElement @ react-dom.development.js:28465
reconcileSingleElement @ react-dom.development.js:15750
reconcileChildFibers @ react-dom.development.js:15808
reconcileChildren @ react-dom.development.js:19167
finishClassComponent @ react-dom.development.js:19782
updateClassComponent @ react-dom.development.js:19698
beginWork @ react-dom.development.js:21611
callCallback @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27451
performUnitOfWork @ react-dom.development.js:26560
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
recoverFromConcurrentError @ react-dom.development.js:25850
performConcurrentWorkOnRoot @ react-dom.development.js:25750
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
react-dom.development.js:18687 The above error occurred in the <ErrorBoundary> component:

    at ErrorBoundary (https://dev.albasim.ch/wegas-react/dist/player.js:31027:86)
    at div
    at https://dev.albasim.ch/wegas-react/dist/player.js:24419:22
    at ComponentContainer (https://dev.albasim.ch/wegas-react/dist/player.js:26117:30)
    at PageDeserializer (https://dev.albasim.ch/wegas-react/dist/player.js:26718:22)
    at div
    at Suspense
    at div
    at ThemeProvider (https://dev.albasim.ch/wegas-react/dist/player.js:29273:23)
    at DndProvider (https://dev.albasim.ch/wegas-react/dist/player.js:356903:11)
    at DefaultDndProvider (https://dev.albasim.ch/wegas-react/dist/player.js:19321:23)
    at PageLoader (https://dev.albasim.ch/wegas-react/dist/player.js:38188:29)
    at Player (https://dev.albasim.ch/wegas-react/dist/player.js:39112:60)
    at div
    at ThemeProvider (https://dev.albasim.ch/wegas-react/dist/player.js:29273:23)
    at PlayerLibrariesLoader (https://dev.albasim.ch/wegas-react/dist/player.js:20661:92)
    at ClassesHandler (https://dev.albasim.ch/wegas-react/dist/player.js:19261:23)
    at LanguagesContext (https://dev.albasim.ch/wegas-react/dist/player.js:19538:23)
    at ServerStatusManager (https://dev.albasim.ch/wegas-react/dist/player.js:28750:24)
    at FullscreenProvider (https://dev.albasim.ch/wegas-react/dist/player.js:19484:23)
    at FeaturesContext (https://dev.albasim.ch/wegas-react/dist/player.js:19373:23)
    at AuthorizationContext (https://dev.albasim.ch/wegas-react/dist/player.js:19115:23)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
logCapturedError @ react-dom.development.js:18687
update.callback @ react-dom.development.js:18720
callCallback @ react-dom.development.js:13923
commitUpdateQueue @ react-dom.development.js:13944
commitLayoutEffectOnFiber @ react-dom.development.js:23391
commitLayoutMountEffects_complete @ react-dom.development.js:24688
commitLayoutEffects_begin @ react-dom.development.js:24674
commitLayoutEffects @ react-dom.development.js:24612
commitRootImpl @ react-dom.development.js:26823
commitRoot @ react-dom.development.js:26682
finishConcurrentRender @ react-dom.development.js:25892
performConcurrentWorkOnRoot @ react-dom.development.js:25809
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
react-dom.development.js:28439 Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `PageDeserializer`.
    at createFiberFromTypeAndProps (react-dom.development.js:28439:1)
    at createFiberFromElement (react-dom.development.js:28465:1)
    at reconcileSingleElement (react-dom.development.js:15750:1)
    at reconcileChildFibers (react-dom.development.js:15808:1)
    at reconcileChildren (react-dom.development.js:19167:1)
    at finishClassComponent (react-dom.development.js:19782:1)
    at updateClassComponent (react-dom.development.js:19698:1)
    at beginWork (react-dom.development.js:21611:1)
    at beginWork$1 (react-dom.development.js:27426:1)
    at performUnitOfWork (react-dom.development.js:26560:1)
createFiberFromTypeAndProps @ react-dom.development.js:28439
createFiberFromElement @ react-dom.development.js:28465
reconcileSingleElement @ react-dom.development.js:15750
reconcileChildFibers @ react-dom.development.js:15808
reconcileChildren @ react-dom.development.js:19167
finishClassComponent @ react-dom.development.js:19782
updateClassComponent @ react-dom.development.js:19698
beginWork @ react-dom.development.js:21611
beginWork$1 @ react-dom.development.js:27426
performUnitOfWork @ react-dom.development.js:26560
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
recoverFromConcurrentError @ react-dom.development.js:25850
performConcurrentWorkOnRoot @ react-dom.development.js:25750
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533

```
